Repository dyninst/testsuite, pull requests merged in 2020-08, with the labels that each got.

#151 Add -dry-run and -exclude
  src/CmdLine.C
  src/help.h
  src/test_driver.C
Labels: enhancement

#100 Fix farcall test
  src/instruction/test_instruction_farcall.C
Labels: bug

#158 Return non-zero from runTests on error
  src/runTests.C
Labels: bug

#146 Make test suite buildable with Clang
  src/dyninst/test1_3.C
Labels: bug, build
